name: bepsy
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.2.2
  - pytorch-cuda=12.1
  - numpy=1.26.4
  - scipy=1.12.0
  - scikit-learn=1.4.2
  - pyyaml=6.0.1
